version: "3.8"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www/html
    environment:
      - CACHE_STORE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CLIENT=phpredis
      - QUEUE_CONNECTION=redis
      - SWAPI_EXTERNAL_API_URL=https://swapi.dev/api
      - SWAPI_CACHE_TTL=3600
      - APP_KEY=base64:placeholder
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/swapi
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
